VERIFY_DEVICE = 0
UPDATE_CONTROLLER = 1
FILE_TRANSFER = 2
CONTROLLER_SETTINGS = 3
WIRELESS_SETTINGS = 4
AP_SETTINGS = 5
ETHERNET_SETTINGS = 6
CONTROLLER_PROGRAMS = 7
WWAN_SETTINGS = 8
CAN_SETTINGS = 9
CONTROLLER_CONFIGURATION = 10
MODULE_SETTINGS = 11
REQUEST_ENABLED_FEATURES = 12
SERVER_ERROR = 13
REBOOT_CONTROLLER = 254
UNKNOWN_COMMAND = 255

#Verify device
DEVICE_VERIFICATION_SUCCESS = 0
DEVICE_VERIFICATION_MISSING = 1
DEVICE_VERIFICATION_INCORRECT_PASSKEY = 2
DEVICE_VERIFICATION_EXCHANGE_KEY = 3
DEVICE_VERIFICATION_ATTEMPT = 4
DEVICE_VERIFICATION_FILE_MISSING = 5

#Update controller
CHECK_FOR_UPDATE = 0
CONTROLLER_INTERNET_ACCESS_FALSE = 1
CONTROLLER_INTERNET_ACCESS_TRUE = 2
UPDATE_CONTROLLER_LOCAL = 3
UPDATE_LOCAL_SUCCESS = 4
UPDATE_FILE_CORRUPTED = 5
UPDATE_FILE_APROVED = 6
UPDATE_FILE_NOT_SENT = 7
UPDATE_VERSION_FILE_MISSING = 8
UPDATE_LOCAL_FAILED = 9


#check for update
CONTROLLER_UPDATE_AVAILABLE = 0
#

#transfer file
FILE_TRANSFER_ENABLED = 0
FILE_TRANSFER_COMPLETE = 1
FILE_TRANSFER_PROGRESS = 2
NO_FILE_RECEIVED = 3
#

#ethernet settings
INIT_ETHERNET_SETTINGS = 0
SET_ETHERNET_SETTINGS = 1
SWITCH_ETHERNET_MODE = 2
#

#wireless settings
INIT_WIRELESS_SETTINGS = 0
GET_WIFI_NETWORKS = 1
GET_CONNECTED_DEVICES = 2
CONNECT_TO_WIFI = 3
DISCONNECT_FROM_WIFI = 4
SWITCH_WIRELESS_MODE = 5

#WiFi connect results
WIFI_CONNECT_FAILED_INC_SSID = 0
WIFI_CONNECT_FAILED_INC_PW = 1
WIFI_CONNECT_SUCCESS = 2
WIFI_CONNECT_FAILED_UNKNOWN = 3

#WiFi disconnect results
WIFI_DISCONNECT_FAILED = 0
WIFI_DISCONNECT_SUCCESS = 1
#

#access point settings
INIT_AP_SETTINGS = 0
SET_AP_SETTINGS = 1
#

#controller settings
INIT_CONTROLLER_SETTINGS = 0
SET_CONTROLLER_SETTINGS = 1
#

#controller programs
INIT_CONTROLLER_PROGRAMS = 0
SET_CONTROLLER_PROGRAMS = 1
#

#wwan settings
INIT_WWAN_SETTINGS = 0
SWITCH_WWAN = 1
SET_WWAN_SETTINGS = 2
#

#can settings
INIT_CAN_SETTINGS = 0
SET_CAN_BAUDRATE = 1
CAN_BUS_LOAD = 2
SET_CAN_STATE = 3
#

#controller configuration
INIT_CONTROLLER_CONFIGURATION = 0
ACQUIRE_MODULE_INFORMATION = 1
#

#module settings
INIT_MODULE_SETTINGS = 0
SET_NEW_FIRMWARE = 1
NEW_FIRMWARE_UPLOAD_COMPLETE = 2
NO_MODULES_TO_UPDATE = 3
ERROR_UPLOADING_FIRMWARE = 4
#

#request enabled features
INIT_FEATURES = 0
FEATURES_APROVED = 1