#!/bin/bash

# url to bash this script:
# wget -O - https://raw.githubusercontent.com/Rick-GO/GOcontroll-Moduline/master/installer/gocontroll-first-install | bash -s master

YELLOW='\033[33m'
NORMAL='\033[0m'

# starting with updating the repositories
echo -e "${YELLOW}Update repositories before we do a system update ${NORMAL}"
apt-get update

# Jump to root folder
cd 

# check if the GOcontroll folder on root already exists. If existing, delete
if [ -d GOcontroll ]
then
echo -e "${YELLOW}Delete existing GOcontroll folder ${NORMAL}"
	rm -r GOcontroll
fi

# Create ne empty GOcontroll folder
echo -e "${YELLOW}Create new GOcontroll folder ${NORMAL}"
mkdir GOcontroll

# Jump to GOcontroll folder
cd GOcontroll
ls

# Download the GOcontroll Moduline GIT repository:
echo -e "${YELLOW} Download files for GOcontroll Moduline ${NORMAL}"
git clone https://github.com/Rick-GO/GOcontroll-Moduline.git --branch $1


echo -e "${YELLOW}Copy specific files to Platform ${NORMAL}"
## Store the new folders/files
cp -avr /root/GOcontroll/GOcontroll-Moduline/lib /
cp -avr /root/GOcontroll/GOcontroll-Moduline/etc /
cp -avr /root/GOcontroll/GOcontroll-Moduline/usr /
cp -avr /root/GOcontroll/GOcontroll-Moduline/root /

## Assign executable rights to file
chmod 755 /usr/scripts/simulink.sh
chmod 755 /usr/scripts/simcom-start.sh
chmod 755 /usr/local/bin/qmi-network-raw
chmod 755 /usr/moduline/simcom-start.hex
chmod 755 /usr/moduline/simcom-stop.hex

# check if the mem-sim folder exists, if so, delete
if [ -d /usr/mem-sim ]
then
echo -e "${YELLOW} Delete existing mem-sim folder ${NORMAL}"
	rm -r /usr/mem-sim
fi

# Create folder to store all shared values in
mkdir /usr/mem-sim

echo -e "${YELLOW}Activate modules for wifi ${NORMAL}"
depmod

echo -e "${YELLOW}Activate Services for wifi ${NORMAL}"
service hostapd start
service dnsmasq start

# Stop node-red service before going further
echo -e "${YELLOW}Stop Node-RED ${NORMAL}"
systemctl stop nodered

echo -e "${YELLOW}Jump node Node RED folder on root ${NORMAL}"
cd ~/.node-red

echo -e "${YELLOW}Install local node packages ${NORMAL}"
# It seems that NPM not always installs AND builds the dependencies again. It is important to delete
# the node modules first and then also delete the package.lock.json file!
# https://stackoverflow.com/questions/18401606/npm-doesnt-install-module-dependencies

npm install --unsafe-perm /usr/node-red-gocontroll

echo -e "${YELLOW}Install Node-RED dashboard ${NORMAL}"
npm install node-red-dashboard

# echo -e "${YELLOW}Enable Node-RED service ${NORMAL}"
# systemctl enable nodered.service 

# echo -e "${YELLOW}Enable SIMCOM device service ${NORMAL}"
# systemctl enable simcom.service 

echo -e "${YELLOW}Reboot controller ${NORMAL}"
reboot
