#!/bin/bash

# url to bash this script:
# wget -O - https://raw.githubusercontent.com/Rick-GO/GOcontroll-Moduline/master/installer/gocontroll-first-install | bash -s master

YELLOW='\033[33m'
NORMAL='\033[0m'

cd 

if [ -d GOcontroll ]
then
echo -e "${YELLOW}-Delete existing GOcontroll folder ${NORMAL}"
	rm -r GOcontroll
fi

echo -e "${YELLOW}-Create new GOcontroll folder ${NORMAL}"
mkdir GOcontroll

cd GOcontroll
ls

if ! [ -x "$(command -v git)" ]; then
echo -e "${YELLOW}-Git is not yet installed so let's install first ${NORMAL}"
apt -y install git 
fi

echo -e "${YELLOW}-Download files for GOcontroll Moduline ${NORMAL}"
git clone https://github.com/Rick-GO/GOcontroll-Moduline.git --branch $1

echo -e "${YELLOW}-Copy specific files to Platform ${NORMAL}"

echo -e "${YELLOW}-Copy GOcontroll files to correct location ${NORMAL}"
cp -avr /root/GOcontroll/GOcontroll-Moduline/lib /
cp -avr /root/GOcontroll/GOcontroll-Moduline/etc /
cp -avr /root/GOcontroll/GOcontroll-Moduline/usr /
cp -avr /root/GOcontroll/GOcontroll-Moduline/root /

echo -e "${YELLOW}-Apply hardware specific patches ${NORMAL}"
patch /usr/node-red-gocontroll/nodes/bridge_module.html ~/GOcontroll/GOcontroll-Moduline/patch/bridge_module_html.patch
patch /usr/node-red-gocontroll/nodes/output_module.html ~/GOcontroll/GOcontroll-Moduline/patch/output_module_html.patch
patch /usr/node-red-gocontroll/nodes/input_module_reset.html ~/GOcontroll/GOcontroll-Moduline/patch/input_module_reset_html.patch
patch /usr/node-red-gocontroll/nodes/input_module.html ~/GOcontroll/GOcontroll-Moduline/patch/input_module_html.patch
patch /usr/node-red-gocontroll/nodes/can_receive.html ~/GOcontroll/GOcontroll-Moduline/patch/can_receive_html.patch
patch /usr/node-red-gocontroll/nodes/can_send.html ~/GOcontroll/GOcontroll-Moduline/patch/can_send_html.patch



echo -e "${YELLOW}-Assign correct execution rights to files ${NORMAL}"
chmod 755 /usr/moduline/bash/go-simulink.sh
chmod 755 /usr/moduline/bash/go-wwan-start.sh
chmod 755 /usr/moduline/bash/go-wwan-stop.sh
chmod 755 /usr/moduline/bash/go-gps-start.sh
chmod 755 /usr/moduline/bash/go-gps-stop.sh
chmod 755 /usr/local/bin/qmi-network-raw
chmod 755 /usr/moduline/nodejs-functions/upload_server.js

echo -e "${YELLOW}-Make resolv.conf immutable ${NORMAL}"
chattr +i /etc/resolv.conf

echo -e "${YELLOW}-Create memory allocation folder ${NORMAL}"
mkdir /usr/mem-sim

echo -e "${YELLOW}-Deploy kernel modules ${NORMAL}"
depmod
insmod /lib/modules/5.10.9-1.0.0+g7f1c87a753d8/kernel/drivers/net/tun.ko


echo -e "${YELLOW}-Activate Services for wifi ${NORMAL}"
service hostapd start
service dnsmasq start

echo -e "${YELLOW}-Jump node Node RED folder on root ${NORMAL}"
cd ~/.node-red

echo -e "${YELLOW}-Install GOcontroll node packages ${NORMAL}"

# It seems that NPM not always installs AND builds the dependencies again. It is important to delete
# the node modules first and then also delete the package.lock.json file!
# https://stackoverflow.com/questions/18401606/npm-doesnt-install-module-dependencies

npm install --unsafe-perm /usr/node-red-gocontroll

echo -e "${YELLOW}-Install Node-RED dashboard ${NORMAL}"
npm install node-red-dashboard@2.30.0

echo -e "${YELLOW}-Install Node-RED serial port ${NORMAL}"
npm install node-red-node-serialport@0.14.1

cd /usr/moduline/nodejs

npm install

echo -e "${YELLOW}-Autostart Node-RED ${NORMAL}"
systemctl enable nodered
systemctl start nodered

echo -e "${YELLOW}-Start upload server ${NORMAL}"
systemctl enable go-upload-server
systemctl start go-upload-server

echo -e "${YELLOW}-Controller ready ${NORMAL}"
