#!/bin/bash

# url to bash this script:
# wget -O - https://raw.githubusercontent.com/Rick-GO/GOcontroll-Moduline/master/installer/gocontroll-first-install | bash -s master

YELLOW='\033[33m'
NORMAL='\033[0m'

cd 

if [ -d GOcontroll ]
then
echo -e "${YELLOW}-Delete existing GOcontroll folder ${NORMAL}"
	rm -r GOcontroll
fi

echo -e "${YELLOW}-Create new GOcontroll folder ${NORMAL}"
mkdir GOcontroll

cd GOcontroll
ls

if ! [ -x "$(command -v git)" ]; then
echo -e "${YELLOW}-Git is not yet installed so let's install first ${NORMAL}"
apt -y install git 
fi

echo -e "${YELLOW}-Update debian ${NORMAL}"
apt-get update -y

echo -e "${YELLOW}-Download files for GOcontroll Moduline ${NORMAL}"
git clone https://github.com/Rick-GO/GOcontroll-Moduline.git --branch $1

echo -e "${YELLOW}-remove old GOcontroll stuff ${NORMAL}"

if [ -d /usr/node-red-gocontroll/nodes ]
then
echo -e "${YELLOW}-Delete existing GOcontroll nodes ${NORMAL}"
	rm -r /usr/node-red-gocontroll/nodes
fi

if [ -d /usr/node-red-static ]
then
echo -e "${YELLOW}-Delete node red static folder ${NORMAL}"
	rm -r /usr/node-red-static
fi

if [ -d /usr/module-firmware ]
then
echo -e "${YELLOW}-Delete old module firmware ${NORMAL}"
	rm -r /usr/module-firmware 
fi

if [ -d /usr/moduline/bash ]
then
echo -e "${YELLOW}-Delete bash automation scripts ${NORMAL}"
	rm -r /usr/moduline/bash 
fi

if [ -d /usr/moduline/nodejs ]
then
echo -e "${YELLOW}-Delete nodejs scripts ${NORMAL}"
	rm -r /usr/moduline/nodejs 
fi

echo -e "${YELLOW}-Copy GOcontroll files to correct location ${NORMAL}"
cp -avr /root/GOcontroll/GOcontroll-Moduline/lib /
cp -avr /root/GOcontroll/GOcontroll-Moduline/etc /
cp -avr /root/GOcontroll/GOcontroll-Moduline/usr /
cp -avr /root/GOcontroll/GOcontroll-Moduline/root /
cp -avr /root/GOcontroll/GOcontroll-Moduline/version.txt /root

if [[ $(tr -d '\0' < /sys/firmware/devicetree/base/hardware) == "Moduline Mini V1.03" ]] ||
[[ $(tr -d '\0' < /sys/firmware/devicetree/base/hardware) == "Moduline Mini V1.04" ]]||
[[ $(tr -d '\0' < /sys/firmware/devicetree/base/hardware) == "Moduline Mini V1.05" ]]; then

echo -e "${YELLOW}-Apply patches for Moduline Mini ${NORMAL}"
patch /usr/node-red-gocontroll/nodes/bridge_module.html ~/GOcontroll/GOcontroll-Moduline/patch/bridge_module_html.patch
patch /usr/node-red-gocontroll/nodes/output_module.html ~/GOcontroll/GOcontroll-Moduline/patch/output_module_html.patch
patch /usr/node-red-gocontroll/nodes/input_module_reset.html ~/GOcontroll/GOcontroll-Moduline/patch/input_module_reset_html.patch
patch /usr/node-red-gocontroll/nodes/input_module.html ~/GOcontroll/GOcontroll-Moduline/patch/input_module_html.patch
patch /usr/node-red-gocontroll/nodes/can_receive.html ~/GOcontroll/GOcontroll-Moduline/patch/can_receive_html.patch
patch /usr/node-red-gocontroll/nodes/can_send.html ~/GOcontroll/GOcontroll-Moduline/patch/can_send_html.patch

fi

echo -e "${YELLOW}-Assign correct execution rights to files ${NORMAL}"
chmod 555 /usr/moduline/bash/go-simulink.sh
chmod 555 /usr/moduline/bash/go-wwan-start.sh
chmod 555 /usr/moduline/bash/go-wwan-stop.sh
chmod 555 /usr/moduline/bash/go-gps-start.sh
chmod 555 /usr/moduline/bash/go-gps-stop.sh
chmod 555 /usr/local/bin/qmi-network-raw
chmod 555 /usr/moduline/nodejs/upload_server.js
chmod 555 /usr/moduline/nodejs/module-info-gathering.js
chmod 555 /usr/moduline/nodejs/upload-new-module-firmware.js

echo -e "${YELLOW}-Make resolv.conf immutable ${NORMAL}"
chattr +i /etc/resolv.conf

echo -e "${YELLOW}-Create memory allocation folder ${NORMAL}"
mkdir /usr/mem-sim

echo -e "${YELLOW}-Deploy kernel modules ${NORMAL}"
depmod
insmod /lib/modules/5.10.9-1.0.0+g7f1c87a753d8/kernel/drivers/net/tun.ko


echo -e "${YELLOW}-Activate Services for wifi ${NORMAL}"
service hostapd start
service dnsmasq start

echo -e "${YELLOW}-Jump node Node RED folder on root ${NORMAL}"
cd ~/.node-red

echo -e "${YELLOW}-Install GOcontroll node packages ${NORMAL}"

# It seems that NPM not always installs AND builds the dependencies again. It is important to delete
# the node modules first and then also delete the package.lock.json file!
# https://stackoverflow.com/questions/18401606/npm-doesnt-install-module-dependencies

npm install --unsafe-perm /usr/node-red-gocontroll

echo -e "${YELLOW}-Install Node-RED dashboard ${NORMAL}"
npm remove --no-audit --no-update-notifier --no-fund --save node-red-dashboard
npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-dashboard@3.1.2
# deprecated way of installing node red dashboard.
# npm install node-red-dashboard@3.1.2

echo -e "${YELLOW}-Install Node-RED serial port ${NORMAL}"
npm remove --no-audit --no-update-notifier --no-fund --save node-red-node-serialport
npm install --no-audit --no-update-notifier --no-fund --save --save-prefix=~ --production --engine-strict node-red-node-serialport@0.15.0
# deprecated way of installing serial port.
# npm install node-red-node-serialport@0.15.0

cd /usr/moduline/nodejs

npm install

echo -e "${YELLOW}-Autostart Node-RED ${NORMAL}"
systemctl enable nodered
systemctl restart nodered

echo -e "${YELLOW}-Start upload server ${NORMAL}"
systemctl enable go-upload-server
systemctl start go-upload-server

echo -e "${YELLOW}-Set time zone ${NORMAL}"
timedatectl set-timezone Europe/Luxembourg

if [ ! -f "/etc/NetworkManage/system-connections/GO-celular.nmconnection" ]
then
	nmcli connection add type gsm ifname 'cdc-wdm0' con-name 'GO-celular' apn 'super' connection.autoconnect yes gsm.pin 0000
fi

python3 /usr/moduline/python/installModuleFirmware.py
 
echo -e "${YELLOW}-Controller ready ${NORMAL}"
